version: 2
updates:
  - package-ecosystem: "nuget"
    directory: "/"
    schedule:
      interval: "daily"
    assignees:
      - "Saalvage"
    reviewers:
      - "Saalvage"
    labels:
      - "dependencies"
      
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"
    assignees:
      - "Saalvage"
    reviewers:
      - "Saalvage"
    labels:
      - "dependencies"
