name: Continuous Integration

on:
  push:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup .NET
        uses: actions/setup-dotnet@v2
        with:
          dotnet-version: '6.0.x'
          
      - name: Setup Entity Framework
        run: dotnet tool install --global dotnet-ef
          
      - name: Setup PostgreSQL
        uses: Harmon758/postgresql-action@v1
        with:
          postgresql user: user
          postgresql password: password
          
      - name: Setup database
        run: dotnet ef database update --project Backend/Backend.csproj

      - name: Build
        run: dotnet build -warnaserror /p:DefineConstants=CI
        
      - name: Setup Playwright
        shell: pwsh
        run: PlaywrightTests/bin/Debug/net6.0/playwright.ps1 install

      - name: Run tests
        run: dotnet test
        
