name: Continuous Integration

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup .NET
        uses: actions/setup-dotnet@v2
        with:
          dotnet-version: '6.0.x'

      - name: Build
        run: dotnet build -warnaserror

      - name: Run tests
        run: dotnet test
        
      - name: Resharper
        uses: glassechidna/resharper-action@v1
        with:
          solution: Atria.sln
